---
# tasks file for myrole1
- name: Update all host/vm packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: yes
    cache_valid_time: 3600
    state: latest
- name: install apache httpd
  ansible.builtin.apt:
    name: apache2
    state: present 
    update_cache: yes
- name: copy file and owner permissions 
  ansible.builtin.copy:
    src: files/index.html
    dest: /var/www/html
    owner: root
    group: root
    mode: '0644'